swagger: '2.0'
host: localhost:40563
basePath: /
schemes:
  - http
produces:
  - application/json
info:
  version: "1.0.0"
  title: Test
paths:
  /upload:
    post:
      summary: Uploads a file.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
      responses:
        200:
          description: File Uploaded
  /file.csv:
    get:
      produces:
        - application/octet-stream
      responses:
        200:
          description: file