// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetFileOKCode is the HTTP code returned for type GetFileOK
const GetFileOKCode int = 200

/*GetFileOK file

swagger:response getFileOK
*/
type GetFileOK struct {
}

// NewGetFileOK creates GetFileOK with default headers values
func NewGetFileOK() *GetFileOK {

	return &GetFileOK{}
}

// WriteResponse to the client
func (o *GetFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
