// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetFileCsvOKCode is the HTTP code returned for type GetFileCsvOK
const GetFileCsvOKCode int = 200

/*GetFileCsvOK file

swagger:response getFileCsvOK
*/
type GetFileCsvOK struct {
}

// NewGetFileCsvOK creates GetFileCsvOK with default headers values
func NewGetFileCsvOK() *GetFileCsvOK {

	return &GetFileCsvOK{}
}

// WriteResponse to the client
func (o *GetFileCsvOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
