// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Test

    Schemes:
      http
    Host: localhost:40563
    BasePath: /
    Version: 1.0.0

    Consumes:
    - multipart/form-data

    Produces:
    - application/json
    - application/octet-stream

swagger:meta
*/
package restapi
